behaviors:
  VisionBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: /Users/jeffrey/Documents/GitHub/Neural-Network-Unity-Games/ComputerVisionProject/Assets/Demonstrations/VisionBehavior.demo
    behavioral_cloning:
      strength: 0.5
      demo_path: /Users/jeffrey/Documents/GitHub/Neural-Network-Unity-Games/ComputerVisionProject/Assets/Demonstrations/VisionBehavior.demo
    max_steps: 800000
    time_horizon: 64
    summary_freq: 10000